- name: yum-utils
  yum:
    name: yum-utils
    state: present

- name: add docker repo
  shell: |
    yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

- name: install docker-ce
  yum:
    name: docker-ce-20.10.1-3.el7
    state: present

- name: update daemon config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart_docker

- name: enable docker
  service:
    name: docker
    state: started
    enabled: true

- name: get docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.2.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
    force: false
