# 需要从github下载docker-compose，网速较慢，注意超时问题
# ansible-playbook  006-setup-docker.yaml  -T  4

---
- hosts: 127.0.0.1
  gather_facts: false
  remote_user: root
  tasks:
    - name: yum-utils
      yum:
        name: yum-utils
        state: present

    - name: add docker repo
      shell: |
        yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

    - name: install docker-ce
      yum:
        name: docker-ce-20.10.1-3.el7
        state: present

    - name: enable docker
      service:
        name: docker
        state: started
        enabled: true

    - name: update docker daemon
      shell: |
        cat > /etc/docker/daemon.json << EOF
        {
          "registry-mirrors": [
            "https://hub-mirror.c.163.com",
            "https://mirror.baidubce.com"
          ]
        }
        EOF
        systemctl restart docker

    - name: get docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
        force: yes

