---
- hosts: 127.0.0.1
  remote_user: root
  gather_facts: false
  tasks:
    - name: restart service
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - crond
        - docker
      tags:
        - restart-service

    - name: add multi users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
        create_home: true
      with_items:
        - { name: 'user1', uid: '2001' }
        - { name: 'user2', uid: '2002' }
        - { name: 'user3', uid: '2003' }
      tags:
        - add-users



# tags 适用于调试模式
# --skip-tags 跳过指定标签
# -t --tags 运行指定标签

# ansible-palybook xxx.yaml --list-tags
# ansible-palybook xxx.yaml  -t add-users

