- name: basic path
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items: "{{ gitlab_file_path }}"

- name: pull docker image
  shell: |
    docker pull gitlab/gitlab-ee:{{ gitlab_version }}

- name: copy docker-compose yaml
  template:
    src: docker-compose.yaml.j2
    dest: /data/dockerImages/gitlab/docker-compose.yaml
  notify:
    - stop_docker_gitlab
    - start_docker_gitlab

- name: update_gitlabrb
  copy:
    src: gitlab.rb
    dest: /data/dockerImages/gitlab/config/gitlab.rb
    mode: '0644'
