---
- hosts: 192.168.31
  remote_user: root
  tasks:
    - name: update hostname
      hostname:
        name: master1.k8s
    - name: add hosts
      lineinfile: name=/etc/hosts line="192.168.1.31 master1.k8s"

- hosts: 192.168.115
  remote_user: root
  tasks:
    - name: update hostname
      hostname:
        name: master2.k8s
    - name: add hosts
      lineinfile: name=/etc/hosts line="192.168.1.115 master2.k8s"
    - name: check hostname and hosts
      shell: |
        hostname
        cat /etc/hosts
      register: check_host_result
    - debug:
        var: check_host_result.stdout_lines

- hosts: 192.168.33
  remote_user: root
  tasks:
    - name: update hostname
      hostname:
        name: w1.k8s
    - name: add hosts
      lineinfile: name=/etc/hosts line="192.168.1.33 w1.k8s"
    - name: check hostname and hosts
      shell: |
        hostname
        cat /etc/hosts
      register: check_host_result
    - debug:
        var: check_host_result.stdout_lines


- hosts: 192.168.34
  remote_user: root
  tasks:
    - name: update hostname
      hostname:
        name: w2.k8s
    - name: add hosts
      lineinfile: name=/etc/hosts line="192.168.1.34 w2.k8s"
    - name: check hostname and hosts
      shell: |
        hostname
        cat /etc/hosts
      register: check_host_result
    - debug:
        var: check_host_result.stdout_lines



- hosts: 192.168.116
  remote_user: root
  tasks:
    - name: update hostname
      hostname:
        name: w3.k8s
    - name: add hosts
      lineinfile: name=/etc/hosts line="192.168.1.116 w3.k8s"
    - name: check hostname and hosts
      shell: |
        hostname
        cat /etc/hosts
      register: check_host_result
    - debug:
        var: check_host_result.stdout_lines



- hosts: 192.168.117
  remote_user: root
  tasks:
    - name: update hostname
      hostname:
        name: w4.k8s
    - name: add hosts
      lineinfile: name=/etc/hosts line="192.168.1.117 w4.k8s"
    - name: check hostname and hosts
      shell: |
        hostname
        cat /etc/hosts
      register: check_host_result
    - debug:
        var: check_host_result.stdout_lines

