---
- hosts: 127.0.0.1
  remote_user: root
  vars:
    base_url_7: https://mirrors.aliyun.com/centos/7/os/x86_64/
    epel_url_7: https://mirrors.aliyun.com/epel/7/x86_64/
  tasks:
    - name: "backup repo"
      copy:
        src: "/etc/yum.repos.d"
        dest: "/etc/yum.repos.d_bak"
        backup: yes
        force: true

    - name: clean old repo
      file:
        path: /etc/yum.repos.d/*
        state: absent

    - name: config base
      yum_repository:
        name: base
        baseurl: "{{ base_url_7 }}"
        enabled: yes
        gpgcheck: no
        mode: 0644
        file: Base
        description: base
        state: present
      when: >
        ansible_facts["distribution"] == "CentOS" and
        ansible_facts["distribution_major_version"] == "7"
    - name: update cache
      shell: |
        yum clean all
        yum makecache

    - name: config epel
      yum_repository:
        name: epel
        baseurl: "{{ epel_url_7 }}"
        enabled: yes
        gpgcheck: no
        mode: 0644
        file: Epel
        description: epel
        state: present
      when: >
        ansible_facts["distribution"] == "CentOS" and
        ansible_facts["distribution_major_version"] == "7"
    - name: update cache
      shell: |
        yum clean all
        yum makecache