- name: basic path
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  with_items: "{{ gitlabrunner_file_path }}"

- name: pull docker image
  shell: |
    docker pull gitlab/gitlab-runner:{{ gitlabrunner_version }}

- name: copy docker-compose yaml
  template:
    src: docker-compose.yaml.j2
    dest: /data/dockerImages/gitlab-runner/docker-compose.yaml
  notify:
    - stop_docker_gitlabrunner
    - start_docker_gitlabrunner

- name: start docker gitlabrunner
  shell: |
    docker-compose -f /data/dockerImages/gitlab-runner/docker-compose.yaml up -d

